<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Employees - {{ $company->name }}</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 24px;
        }

        .header {
            border-bottom: 2px solid #333;
            padding-bottom: 16px;
            margin-bottom: 24px;
        }

        .header table {
            width: 100%;
            border-collapse: collapse;
        }

        .header td {
            vertical-align: middle;
        }

        .header .logo-cell {
            width: 100px;
            text-align: left;
        }

        .header .logo-cell img {
            max-width: 80px;
            max-height: 80px;
        }

        .header .info-cell {
            text-align: left;
            padding-left: 16px;
        }

        .header h1 {
            font-size: 20px;
            margin: 0 0 4px 0;
            color: #222;
        }

        .header .company-meta {
            font-size: 11px;
            color: #666;
            line-height: 1.4;
        }

        .doc-title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin: 24px 0 12px 0;
            color: #222;
        }

        .meta-bar {
            font-size: 10px;
            color: #888;
            text-align: right;
            margin-bottom: 8px;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        table.data th,
        table.data td {
            border: 1px solid #999;
            padding: 8px 10px;
            text-align: left;
            vertical-align: top;
        }

        table.data th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 11px;
        }

        table.data td {
            font-size: 11px;
        }

        table.data tr:nth-child(even) td {
            background-color: #fafafa;
        }

        .col-no {
            width: 40px;
            text-align: center;
        }

        .empty-state {
            text-align: center;
            padding: 32px;
            color: #888;
            font-style: italic;
        }

        .footer {
            margin-top: 32px;
            font-size: 10px;
            color: #888;
            text-align: center;
            border-top: 1px solid #ccc;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td class="logo-cell">
                    @if ($logoBase64)
                        <img src="{{ $logoBase64 }}" alt="Logo">
                    @endif
                </td>
                <td class="info-cell">
                    <h1>{{ $company->name }}</h1>
                    <div class="company-meta">
                        Email: {{ $company->email }}<br>
                        Website: {{ $company->website }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <div class="doc-title">Daftar Employee</div>

    <div class="meta-bar">
        Total: {{ $employees->count() }} employee &middot;
        Generated: {{ $generatedAt->format('d M Y H:i') }}
    </div>

    @if ($employees->isEmpty())
        <div class="empty-state">
            Belum ada employee untuk company ini.
        </div>
    @else
        <table class="data">
            <thead>
                <tr>
                    <th class="col-no">No</th>
                    <th>Nama</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($employees as $index => $employee)
                    <tr>
                        <td class="col-no">{{ $index + 1 }}</td>
                        <td>{{ $employee->name }}</td>
                        <td>{{ $employee->email }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        {{ $company->name }} &middot; Document generated by system
    </div>
</body>
</html>
